# Generated by Django 4.1.1 on 2022-09-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="test",
            field=models.URLField(default="sd"),
        ),
    ]
