# Generated by Django 4.1.4 on 2022-12-24 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs", "0002_alter_comment_blog_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blogs.blog",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userComment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
