# Generated by Django 4.1.4 on 2022-12-24 11:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_comment_blog_alter_comment_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
