# Generated by Django 4.1.4 on 2022-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=300, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("avatar", models.ImageField(blank=True, upload_to="avatar")),
                ("designation", models.CharField(blank=True, max_length=200)),
                ("about", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, null=True)),
                ("learning", models.CharField(blank=True, max_length=200)),
                ("available_for", models.CharField(blank=True, max_length=200)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
