# Generated by Django 4.1.3 on 2022-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_available_for_alter_user_learning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
